# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.niningxiaoshi.site
date_format: "ordinal"
title: 闪光的沙粒
subtitle: "长风破浪会有时"
description: "小磊的个人博客"
keywords: 闪光的沙粒, Lei Yang, Bradley, yanglei
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Lei Yang
organization: 
organization_url: 
github_username: Bradley-dufe
location: Beijing, China
email: niningxiaoshi@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge

paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Bradley-dufe/bradley.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner:
    repo:
    oauth:
        client_id:
        client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Bradley-dufe
    repo: blog-comments
    clientID: e5c24a09874cf61b51ff
    clientSecret: b277cd50d3a51aaa778d434f6243613b66d14020
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id:
